const state={tab:"landing",imageData:""};const $=id=>document.getElementById(id);
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.tab=b.dataset.tab;updateTitle()});
$("imageInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;$("imageName").textContent=f.name;const r=new FileReader();r.onload=()=>{$("previewImg").src=r.result;state.imageData=r.result;$("preview").classList.remove("hidden")};r.readAsDataURL(f)};
$("generateBtn").onclick=generate;$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText($("output").value);$("notice").textContent="Copied to clipboard."};$("downloadBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([$("output").value],{type:"text/plain"}));a.download="affiliate-campaign.txt";a.click();URL.revokeObjectURL(a.href)};$("videoBtn").onclick=()=>{state.tab="tiktok";document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab==="tiktok"));$("output").value=videoBrief(data());updateTitle()};
function data(){return{n:$("productName").value.trim()||"Smart Home Security Product",u:$("affiliateUrl").value.trim()||"[INSERT AFFILIATE LINK]",d:$("description").value.trim()||"Modern security technology designed to support a safer, more connected home.",m:$("market").value,c:$("channel").value}}
function updateTitle(){const x={landing:"Premium Landing Page",tiktok:"TikTok • 9:16",facebook:"Facebook Campaign",pinterest:"Pinterest Pin"};$("outputTitle").textContent=x[state.tab]}
async function generate(){const p=data();$("mode").textContent="GENERATING";$("notice").textContent="Building your premium campaign…";try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,tab:state.tab})});const j=await r.json();if(!r.ok||!j.output)throw Error();$("output").value=j.output;$("mode").textContent="AI MODE";$("notice").textContent="Campaign generated."}catch(e){$("output").value=local(p);$("mode").textContent="LOCAL MODE";$("notice").textContent="Local generator used. Connect an AI provider for richer generation."}updateTitle()}
function local(p){if(state.tab==="landing")return `HEADLINE\nSmarter Security. Greater Peace of Mind.\n\nPRODUCT\n${p.n}\n\nPOSITIONING\nDiscover a practical security upgrade for your home, built around modern features and everyday confidence.\n\nPRODUCT MESSAGE\n${p.d}\n\nCTA\nDiscover Product → ${p.u}\n\nMARKET\n${p.m}\n\nAFFILIATE DISCLOSURE\nThis content may contain affiliate links. We may earn a commission from qualifying purchases.`;if(state.tab==="tiktok")return videoBrief(p);if(state.tab==="facebook")return `FACEBOOK POST\n\nYour home deserves smarter protection.\n\nMeet ${p.n} — a modern home-security option designed around convenience, awareness and peace of mind.\n\n${p.d}\n\nDiscover Product → ${p.u}\n\n#HomeSecurity #SmartHome #HomeProtection`;return `PINTEREST PIN\n\n${p.n}\n\nSmart home security inspiration for a safer, more connected home.\n\n${p.d}\n\nDiscover Product → ${p.u}\n\nKeywords: home security, smart home, security technology, home protection`}
function videoBrief(p){return `TIKTOK 9:16 VIDEO BRIEF\n\nHOOK (0–3s)\n“Could your home security be smarter?”\n\nSCENE 1 (3–7s)\nShow the real product image with a clean premium zoom.\n\nSCENE 2 (7–13s)\nHighlight: ${p.d}\n\nSCENE 3 (13–18s)\nShow the product in a modern home-security context with concise benefit text.\n\nCTA (18–22s)\n“Discover the product — link in bio.”\n\nCAPTION\nUpgrade the way you think about home security with ${p.n}.\n\nAFFILIATE URL\n${p.u}\n\nFORMAT\n9:16 vertical • TikTok / Reels / Shorts`}
updateTitle();